### ISSUE TITLE
Nav Walker adds duplicate class= attr to nav items

### ISSUE THREAD

**Issue by jessedmatlock** [SimonPadbury/b5st#2]
First off, thanks for such a clean, well coded theme.. greatly apprecaited!

Based on the feedback from W3C HTM Validator, I came across this error. 

To duplicate, create a menu with child pages. 

You will see that the child items have duplicate class attributes, such as:
`<li  id="menu-item-39" class="menu-item menu-item-type-post_type menu-item-object-page nav-item nav-item-39"><a class="dropdown-item" href="http://dev.local/page/" class="nav-link">List of Languages</a></li>`

This appears to be created here:
`		$attributes .= ( $args->walker->has_children ) ? ' class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"' : ' class="nav-link"';
		$item_output = $args->before;
		$item_output .= ( $depth > 0 ) ? '<a class="dropdown-item"' . $attributes . '>' : '<a' . $attributes . '>';
`

Where the child item inherits the attributes of the parent, but also adds another class attribute with the value of "dropdown-item".

**Suggested edit:** 

_Change line 44 of navbar.php from:_

`$attributes .= ( $args->walker->has_children ) ? ' class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"' : ' class="nav-link"';`

To:

`$classes = ( $args->walker->has_children ) ? ' class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"' : ' class="nav-link"';`

_AND Line 47 of navbar.php from:_

`$item_output .= ( $depth > 0 ) ? '<a class="dropdown-item"' . $attributes . '>' : '<a' . $attributes . '>';`

To:

`$item_output .= ( $depth > 0 ) ? '<a class="dropdown-item"' . $attributes . '>' : '<a' . $attributes .' '. $classes . '>';`

**Comment by SimonPadbury** [comment]
Thankyou! -- I've just made those changes, plus I updated Bootstrap and icons

**Comment by jessedmatlock** [comment]
Awesome! Just saw that you'd already committed the changes to the repo! Glad to help and thanks for all the hard work

**Comment by SimonPadbury** [comment]
Yes, all done.
