### ISSUE TITLE
Array to string conversion error in navbar.php using PHP 8.0

### ISSUE THREAD

**Issue by shane-hoving-pc** [SimonPadbury/b5st#4]
Full error message: "Warning: Array to string conversion in \app\public\wp-content\themes\theme-name\functions\navbar.php on line 44."

This is only showing up on the site when we upgraded to PHP 8.0. Any ideas on how to fix this?

Thanks!

**Comment by SimonPadbury** [comment]
Hi Shane,

Thanks — I just fixed it. Swap for my new `navbar.php`

https://github.com/SimonPadbury/b5st/blob/main/functions/navbar.php <https://github.com/SimonPadbury/b5st/blob/main/functions/navbar.php>

I just made these changes on my local Flywheel dev server (edited lines 44 and 47), and it’s all working now.

Kind regards,

Simon

**Comment by SimonPadbury** [comment]
Hi Shane,

Actually, you might want to update all (b5st) to v.1.3.1 -- because I just updated Bootstrap to v.5.2.1 and Bootstrap Icons to v.1.9.1

See `functions/enqueues.php`

Slight change to the navbar too.

Simon

**Comment by shane-hoving-pc** [comment]
Thank you @SimonPadbury. That worked perfectly and fixed the issue. I appreciate the quick reply.
